local mason = vim.fn.stdpath 'data' .. '/mason'
local prettier = { 'prettierd', 'prettier', stop_after_first = true }

local js_ts_settings = {
  updateImportsOnFileMove = { enabled = 'always' },
  suggest = { completeFunctionCalls = true },
  inlayHints = {
    enumMemberValues = { enabled = true },
    functionLikeReturnTypes = { enabled = true },
    parameterNames = { enabled = 'literals' },
    parameterTypes = { enabled = true },
    propertyDeclarationTypes = { enabled = true },
    variableTypes = { enabled = false },
  },
}

return {
  servers = {
    lua_ls = {
      settings = {
        Lua = {
          completion = { callSnippet = 'Replace' },
          workspace = { checkThirdParty = false },
        },
      },
    },
    vtsls = {
      filetypes = {
        'javascript',
        'javascriptreact',
        'javascript.jsx',
        'typescript',
        'typescriptreact',
        'typescript.tsx',
      },
      settings = {
        complete_function_calls = true,
        vtsls = {
          enableMoveToFileCodeAction = true,
          autoUseWorkspaceTsdk = true,
          experimental = {
            maxInlayHintLength = 30,
            completion = { enableServerSideFuzzyMatch = true },
          },
          tsserver = {
            globalPlugins = {
              {
                name = '@astrojs/ts-plugin',
                location = mason
                  .. '/packages/astro-language-server/node_modules/@astrojs/ts-plugin',
                enableForWorkspaceTypeScriptVersions = true,
              },
            },
          },
        },
        javascript = js_ts_settings,
        typescript = js_ts_settings,
      },
    },
    eslint = {
      settings = {
        workingDirectories = { mode = 'auto' },
      },
    },
    astro = {},
    pyright = {},
    ruff = {
      init_options = { settings = { logLevel = 'error' } },
    },
    gopls = {
      settings = {
        gopls = {
          gofumpt = true,
          completeUnimported = true,
          usePlaceholders = true,
          staticcheck = true,
          semanticTokens = true,
          analyses = {
            fieldalignment = true,
            nilness = true,
            unusedparams = true,
            unusedwrite = true,
            useany = true,
          },
          codelenses = {
            gc_details = false,
            generate = true,
            regenerate_cgo = true,
            run_govulncheck = true,
            test = true,
            tidy = true,
            upgrade_dependency = true,
            vendor = true,
          },
          hints = {
            assignVariableTypes = true,
            compositeLiteralFields = true,
            compositeLiteralTypes = true,
            constantValues = true,
            functionTypeParameters = true,
            parameterNames = true,
            rangeVariableTypes = true,
          },
          directoryFilters = {
            '-.git',
            '-.idea',
            '-.vscode',
            '-.vscode-test',
            '-node_modules',
          },
        },
      },
    },
    dockerls = {},
    docker_compose_language_service = {},
    tailwindcss = {
      filetypes = {
        'astro',
        'css',
        'html',
        'javascript',
        'javascriptreact',
        'svelte',
        'typescript',
        'typescriptreact',
        'vue',
      },
      settings = {
        tailwindCSS = {
          includeLanguages = {
            elixir = 'html-eex',
            eelixir = 'html-eex',
            heex = 'html-eex',
          },
        },
      },
    },
    cssls = {},
    marksman = {
      filetypes = { 'markdown', 'markdown.mdx', 'mdx' },
    },
  },
  tools = {
    'astro-language-server',
    'css-lsp',
    'docker-compose-language-service',
    'dockerfile-language-server',
    'eslint-lsp',
    'gofumpt',
    'goimports',
    'gopls',
    'hadolint',
    'lua-language-server',
    'markdown-toc',
    'markdownlint-cli2',
    'marksman',
    'prettier',
    'prettierd',
    'pyright',
    'ruff',
    'stylua',
    'tailwindcss-language-server',
    'vtsls',
  },
  parsers = {
    'astro',
    'bash',
    'c',
    'css',
    'diff',
    'dockerfile',
    'go',
    'gomod',
    'gosum',
    'gowork',
    'html',
    'javascript',
    'json',
    'jsonc',
    'lua',
    'luadoc',
    'markdown',
    'markdown_inline',
    'ninja',
    'python',
    'query',
    'rst',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'yaml',
  },
  formatters_by_ft = {
    astro = prettier,
    css = prettier,
    graphql = prettier,
    handlebars = prettier,
    html = prettier,
    javascript = prettier,
    javascriptreact = prettier,
    json = prettier,
    jsonc = prettier,
    less = prettier,
    lua = { 'stylua' },
    markdown = prettier,
    ['markdown.mdx'] = prettier,
    mdx = prettier,
    python = { 'ruff_organize_imports', 'ruff_format' },
    scss = prettier,
    typescript = prettier,
    typescriptreact = prettier,
    vue = prettier,
    yaml = prettier,
    go = { 'goimports', 'gofumpt' },
  },
  linters_by_ft = {
    dockerfile = { 'hadolint' },
    markdown = { 'markdownlint-cli2' },
    ['markdown.mdx'] = { 'markdownlint-cli2' },
    mdx = { 'markdownlint-cli2' },
  },
}
